### ISSUE TITLE
openssl version parsing error

### ISSUE THREAD

**Issue by ThomasWaldmann** [matze/pkgconfig#32]
pkgconfig crashes while checking the openssl version number:
```
>>> pkgconfig.installed('openssl', '>= 1.1.0')
Traceback (most recent call last):
  File "/home/user/w/borg-env/lib/python3.5/site-packages/pkgconfig/pkgconfig.py", line 161, in installed
    result = _compare_versions(modversion, number)
  File "/home/user/w/borg-env/lib/python3.5/site-packages/pkgconfig/pkgconfig.py", line 44, in _compare_versions
    n1 = normalize(v1)
  File "/home/user/w/borg-env/lib/python3.5/site-packages/pkgconfig/pkgconfig.py", line 42, in normalize
    return [int(x) for x in re.sub(r'(\.0+)*$', '', v).split(".")]
  File "/home/user/w/borg-env/lib/python3.5/site-packages/pkgconfig/pkgconfig.py", line 42, in <listcomp>
    return [int(x) for x in re.sub(r'(\.0+)*$', '', v).split(".")]
ValueError: invalid literal for int() with base 10: '0j'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/w/borg-env/lib/python3.5/site-packages/pkgconfig/pkgconfig.py", line 164, in installed
    raise ValueError(msg)
ValueError: >= 1.1.0 is not a correct version specifier
```

It's on Debian 9:
```
ii  openssl                              1.1.0j-1~deb9u1                   amd64        Secure Sockets Layer toolkit - cryptographic utility
```

Note: openssl 1.1 is incompatible to 1.0, so while the check for a specific update release (like `j`) is maybe not that important (except for security fixes, early bug fixes), the check for 1.1 vs. 1.0 is fundamentally important.

**Comment by ThomasWaldmann** [comment]
Any comment? Shall I have a look at fixing this?

**Comment by matze** [comment]
> And ... in case I can fix this, would you make a release afterwards?

Yeah, sure.
